opengovfoundation/madison

app/commands/CreateUser.php, app/controllers/RemindersController.php, app/controllers/UserManageApiController.php
Fixes #545 
"Fixed password rehashing error due to assigning an already hashed password to user, having a mutator on user model"
=> Fixed password rehashing error

app/controllers/UserController.php
=> Fix facebook bug

app/controllers/DocumentApiController.php
=> Fix missing $type variable

app/models/User.php, public/js/controllers/userEditPageController.js, public/templates/pages/user-edit.html
For both Verify Users and Verify Independent Sponsor.  Fixes #704
=> Completely patching up users verification

app/Providers/PdoEventSessionHandlerProvider.php, app/Providers/SessionRejectServiceProvider.php, app/Providers/UserServiceProvider.php, app/Session/Storage/Handler/PdoEventSessionHandler.php, config/app.php, config/session.php
These were missed during the Laravel 5 upgrade.
Close #710 
@cmbirk @krues8dr
=> Pull in files for `database_event` session driver

app/config/database.php, app/config/elasticsearch.php, app/config/example_oauth_creds.php
=> minor codestyle cleanups

public/templates/pages/login.html, public/templates/pages/signup.html
#765
* Using email input type.
* Adding required attribute to required fields.
* Removing placeholders as these should not be used as labels.
@cmbirk @sethetter
=> Cleaning up signup & login pages.

public/templates/partials/doc-stats.html
Fixes #820
@krues8dr @sethetter
=> Include annotation_comments in top-level document comment count.

app/Http/Kernel.php, app/Http/Middleware/DocAccessEdit.php, app/Http/routes.php, app/Models/Group.php, public/js/controllers/dashboardEditorController.js, public/locales/en_US.json
Fixes #828
For the scope of this problem, I've gone ahead and locked down the API routes that should require authorization to edit a particular document. For the issue of accessing the edit screen in angular in the first place I've opened #830.
@cmbirk @krues8dr
=> Issue 828 - unauthorized editing of documents

app/Http/Controllers/DocumentsController.php, app/Http/routes.php, app/Models/Doc.php
@cmbirk @sethetter   This and a symlink gets us #673 I think.
=> Using Storage facade to handle image uploads.  #673

public/templates/partials/doc-comments.html
Quick fix on orderBy.  Fixes #801
=> fix comments out of order.  Now ordered by id in reverse.  Fixes #801

app/Http/Controllers/DocumentApiController.php, app/Http/Controllers/DocumentsController.php
@sethetter @cmbirk that was way easier than I ever would have expected.
=> Cache rendered html.  #863

public/js/controllers/documentPageController.js, public/locales/en_US.json, public/templates/pages/doc.html
Also added a tiny loading indicator
Issue #865
=> Issue 865 - Handle hash links to document content

docs/README.md, public/index.html
and some additions to the Madison setup process
=> Ubuntu installation guide

app/Http/Controllers/DocumentController.php, database/migrations/2016_03_01_023454_doc_slug_not_unique.php
=> Fixes #885

.env.example, docs/README.md
=> Improve documentation of .env file.  #913

public/templates/partials/header.html, tests/client/e2e/layout.spec.js
This really should be all that's actually necessary for #924 right now, afaik?
=> Removing OpenGov-specific links from nav. #924

public/templates/activity-item.html
Is used in other templates, not here
=> Translate copy link

bower.json, public/js/controllers/commentController.js, public/pre-build.html, public/templates/partials/doc-comments.html
Add autolinking. Needs a bower update + rebuild.
Thanks to @abihas
=> Add autolinker

app/Events/UserVerificationStatusChange.php, app/Http/Controllers/UserController.php, app/Listeners/UserVerificationStatusChangeNotification.php, app/Providers/EventServiceProvider.php
Issue #250 
@krues8dr @sethetter 
This has some interaction with things that change in #968, so whichever one gets merged first, the other will need to be rebased before it can be merged.
=> Send notification when a users verification status changes

client/app/locales/en_US.json, client/app/sass/modules/_footer.scss
Issue #988 
@krues8dr @sethetter
=> Add the "powered by" footer line back in for English

public/js/controllers/resendConfirmationController.js
=> Force login and redirect on confirmation.  #963

resources/views/email/signup.blade.php
=> Adding video to confirmation email.  #1008

public/sass/pages/_edit-document.scss
@sethetter @doshitan Quick hotfix for the missing editor buttons.
=> Issue 1006

client/app/locales/en_US.json, client/app/templates/pages/user-notification-settings.html, server/app/Contracts/Event.php, server/app/Events/CommentCreated.php, server/app/Events/FeedbackSeen.php, server/app/Events/GroupCreated.php, server/app/Events/GroupMemberAdded.php, server/app/Events/UserVerificationStatusChange.php, server/app/Http/Controllers/UserController.php
Issue #974 
Haven't had a chance to actually build the client and test this yet, but a rough start.
@krues8dr @sethetter
=> Support localization of event descriptions for notification preferences

.gitignore, Berksfile.lock, Makefile, config/deploy.rb, server/app/Console/Commands/DatabaseBackup.php
* `cap stagename db:backup:create` - creates a backup and stores it on the server
* `cap stagename db:backup:fetch` - creates a backup and downloads it locally
=> Capistrano tasks for db backups (#1051)

Gemfile, Gemfile.lock, client/app/sass/_custom.scss, client/config.rb, config/deploy.rb
`cap stagename client:rebuild`
=> Capistrano task for rebuilding remote client (#1055)
